media:
  input: public/assets/images
  output: /assets/images

content:
  - name: hero-slides
    label: Hero Slides
    type: collection
    path: src/content/hero-slides
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: false
      - name: image
        label: Image
        type: image
      - name: link
        label: Link
        type: string
        required: false
