content:
  - label: "Hero Slides"
    folder: "src/content/hero-slides"
    type: "collection"
    path: "{slug}" # Добавь эту строку, она важна для некоторых версий CMS
    extension: "md"
    format: "frontmatter-md" # Уточняем формат
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          upload_dir: "public/assets/images",
        }
      - { label: "Link", name: "link", widget: "string" }
