content:
  - label: "Hero Slides"
    folder: "src/content/hero-slides"
    type: "collection"
    format: "md"
    fields:
      - label: "Изображение"
        name: "image"
        widget: "image"
        # Путь, куда будут сохраняться новые картинки
        upload_dir: "public/assets/images"
      - label: "Alt текст"
        name: "alt"
        widget: "string"
