content:
  - label: "Слайды в Hero"
    folder: "src/content/hero-slides"
    type: "collection"
    format: "md"
    fields:
      - label: "Изображение"
        name: "image"
        widget: "image"
        upload_dir: "public/assets/images"
      - label: "Заголовок проекта"
        name: "title"
        widget: "string"
      - label: "Ссылка"
        name: "link"
        widget: "string"
      - label: "Alt текст"
        name: "alt"
        widget: "string"
